// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNFlygUZiPqrHdxQEmcw97d7USssbVKZc',
    appId: '1:394469341313:web:73c9c1c5bd92b760243580',
    messagingSenderId: '394469341313',
    projectId: 'involve-2815c',
    authDomain: 'involve-2815c.firebaseapp.com',
    storageBucket: 'involve-2815c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL5DOiWWAGTOtW8tQnJMwY_Kr5cPsZ9_Q',
    appId: '1:394469341313:android:2d6b86b4f0008d2b243580',
    messagingSenderId: '394469341313',
    projectId: 'involve-2815c',
    storageBucket: 'involve-2815c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-O_DgsBOLpRhvTzkCNV6HMHd7fyUk3XA',
    appId: '1:394469341313:ios:2032cb55803fb383243580',
    messagingSenderId: '394469341313',
    projectId: 'involve-2815c',
    storageBucket: 'involve-2815c.firebasestorage.app',
    iosBundleId: 'com.example.involve',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-O_DgsBOLpRhvTzkCNV6HMHd7fyUk3XA',
    appId: '1:394469341313:ios:2032cb55803fb383243580',
    messagingSenderId: '394469341313',
    projectId: 'involve-2815c',
    storageBucket: 'involve-2815c.firebasestorage.app',
    iosBundleId: 'com.example.involve',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNFlygUZiPqrHdxQEmcw97d7USssbVKZc',
    appId: '1:394469341313:web:d7416838cf030c3f243580',
    messagingSenderId: '394469341313',
    projectId: 'involve-2815c',
    authDomain: 'involve-2815c.firebaseapp.com',
    storageBucket: 'involve-2815c.firebasestorage.app',
  );
}
